#spring.application.name=journalApp
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017

#spring.data.mongodb.uri=mongodb+srv://vishnu2000:vishnu%4099@cluster0.ikto3.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.uri=mongodb+srv://vishnu2000:vishnu%4099@cluster0.ikto3.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true
spring.main.allow-bean-definition-overriding=true

